apiVersion: v1
kind: ConfigMap
metadata:
  name: incidentiq-config
data:
  KAFKA_BROKER:       "kafka:9092"
  ES_HOST:            "http://elasticsearch:9200"
  ES_INDEX:           "logs"
  QDRANT_HOST:        "http://qdrant:6333"
  QDRANT_COLLECTION:  "incidents"
  REDIS_HOST:         "redis"
  REDIS_PORT:         "6379"
  API_HOST:           "0.0.0.0"
  API_PORT:           "8000"
  EMBEDDING_MODEL:    "all-MiniLM-L6-v2"
  EMBEDDING_DIM:      "384"
  ANOMALY_THRESHOLD:  "0.5"
  LOG_WINDOW_MINUTES: "5"
  LOG_MAX_FETCH:      "200"
  OPENAI_MODEL:       "gpt-4o-mini"
